spring.application.name=MealDonation
spring.datasource.url: jdbc:postgresql://localhost:5432/mealdonation
spring.jpa.properties.hibernate.default_schema=public
spring.datasource.username: postgres
spring.datasource.password: postgres
spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=wXoL3ktsL8qkeBdV4CJ0N2CS7m5pv9yGQFZ8bP51ys4=

server.port=8080

